using System;
using System.IO;
using System.Text;
using System.Threading.Tasks;

namespace ValheimMoments
{
    internal enum RelayOutcome { Failed = 0, Uploaded = 1, Omitted = 2, Unknown = 3 }
    // One disk reservation and one worker chunk at a time. Paths are generated by
    // the host; a peer's ID is metadata only and never becomes a filesystem path.
    internal sealed class RelayFile : IDisposable
    {
        internal readonly string Id, Kind, Message, FilePath, EventId;
        internal readonly bool PersonalFirst;
        internal readonly int Size;
        internal int Received { get; private set; }
        internal bool Complete { get; private set; }
        private Task<bool> pending;
        private int pendingBytes;
        private bool disposed, failed, ownsFile;

        internal RelayFile(string directory, string id, string kind, string message, int size, int limit, string eventId = null, bool personalFirst = false)
        {
            if (!RelayProtocol.ValidId(id) || !RelayProtocol.ValidKind(kind) || message == null || message.Length > 2000 ||
                size < 20 || size > Math.Min(limit, RelayProtocol.MaxBytes) || (eventId != null && !HighlightDirector.ValidId(eventId))) throw new ArgumentException("Invalid relay offer");
            Id = id; Kind = kind; Message = message; Size = size;
            EventId = eventId; PersonalFirst = personalFirst;
            FilePath = Path.Combine(Path.GetFullPath(directory), Guid.NewGuid().ToString("N") + ".webp");
        }

        internal bool BeginAdd(int offset, byte[] bytes)
        {
            if (disposed || failed || pending != null || Complete || bytes == null || bytes.Length < 1 ||
                bytes.Length > RelayProtocol.ChunkBytes || offset != Received || bytes.Length > Size - Received) return false;
            var owned = (byte[])bytes.Clone(); pendingBytes = owned.Length;
            pending = Task.Run(() => {
                try
                {
                    Directory.CreateDirectory(Path.GetDirectoryName(FilePath));
                    using (var file = new FileStream(FilePath, offset == 0 ? FileMode.CreateNew : FileMode.Open,
                        FileAccess.ReadWrite, FileShare.None, RelayProtocol.ChunkBytes))
                    {
                        if (offset == 0) ownsFile = true;
                        if (file.Length != offset) return false;
                        file.Position = offset; file.Write(owned, 0, owned.Length); file.Flush();
                        return offset + owned.Length != Size || ValidWebP(file, Size);
                    }
                }
                catch { return false; }
            });
            return true;
        }

        // 0: worker pending/no work, -1: failed, 1: chunk persisted, 2: complete.
        internal int Poll()
        {
            if (disposed || pending == null || !pending.IsCompleted) return 0;
            bool success = pending.GetAwaiter().GetResult(); pending = null;
            if (!success) { failed = true; return -1; }
            Received += pendingBytes; pendingBytes = 0; Complete = Received == Size;
            return Complete ? 2 : 1;
        }

        private static bool ValidWebP(Stream file, int size)
        {
            file.Position = 0;
            using (var reader = new BinaryReader(file, Encoding.ASCII, true))
            {
                if (reader.ReadUInt32() != 0x46464952 || reader.ReadUInt32() != (uint)(size - 8) || reader.ReadUInt32() != 0x50424557) return false;
                while (file.Position < size)
                {
                    if (size - file.Position < 8) return false;
                    reader.ReadUInt32(); uint bytes = reader.ReadUInt32();
                    long next = file.Position + bytes + (bytes & 1);
                    if (next > size) return false;
                    file.Position = next;
                }
                return file.Position == size;
            }
        }

        internal static Task<int> Inspect(string path)
        {
            return Task.Run(() => {
                try { using (var file = File.OpenRead(path)) return file.Length >= 20 && file.Length <= RelayProtocol.MaxBytes ? (int)file.Length : 0; }
                catch { return 0; }
            });
        }

        internal static Task<byte[]> ReadChunk(string path, int offset, int size)
        {
            return Task.Run(() => {
                try
                {
                    if (offset < 0 || offset >= size || size > RelayProtocol.MaxBytes) return null;
                    using (var file = File.OpenRead(path))
                    {
                        if (file.Length != size) return null;
                        file.Position = offset;
                        var bytes = new byte[Math.Min(RelayProtocol.ChunkBytes, size - offset)];
                        int read = 0;
                        while (read < bytes.Length) { int n = file.Read(bytes, read, bytes.Length - read); if (n == 0) return null; read += n; }
                        return bytes;
                    }
                }
                catch { return null; }
            });
        }

        internal Task Cleanup { get; private set; }
        public void Dispose()
        {
            if (disposed) return;
            disposed = true;
            // Even reset during a write deletes only after that worker closes its handle.
            Cleanup = (pending ?? Task.FromResult(true)).ContinueWith(_ => {
                try { if (ownsFile) File.Delete(FilePath); } catch { }
            }, TaskScheduler.Default);
        }
    }
}
